// export const GET_DATA_REQUEST="GET_DATA_REQUEST"
// export const GET_DATA_SUCCESS="GET_DATA_SUCCESS"
// export const GET_DATA_ERROR="GET_DATA_ERROR"

export const GET_DATA_REQUEST="GET_DATA_REQUEST"
export const GET_DATA_SUCCESS="GET_DATA_SUCCESS"
export const GET_DATA_ERROR="GET_DATA_ERROR"

export const GET_SINGLE_DATA_LOADING="GET_SINGLE_DATA_LOADING"
export const GET_SINGLE_DATA_SUCCESS="GET_SINGLE_DATA_SUCCESS"
export const GET_SINGLE_DATA_ERROR="GET_SINGLE_DATA_ERROR"