
  
//  POST REQUEST
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const APPLY_PROMO = "APPLY_PROMO";
export const REMOVE_PROMO = "REMOVE_PROMO";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const EMPTY_CART = "EMPTY_CART";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";

